version: '3'

services:
  db:
    image: ankane/pgvector
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db:
